### ISSUE TITLE
Add histogram to metrics_pb2

### ISSUE THREAD

**Issue by claws** [slok/prometheus-python#3]
Could you update the project's `metrics_pb2.py` to contain the full content of the `metrics.proto`? Specifically the Histogram.

I would like to contribute updates that add the Histogram metric. I have a modified version of this package in which I have added the Histogram metrics for both Text and Protobuf formats. However, I am using a Pyrobuf generated version of the `metrics_pb2.py` instead of the one you use (which I assume is the output from the C++ GPB parser). I'm not sure how you create the `metrics_pb2.py` file. 

With a complete `metrics_pb2.py` in place I can ensure any updated tests work before submitting a PR that adds Histogram capabilities.

**Comment by slok** [comment]
Hi!

Well.. this project is out of date, use the official client called: https://github.com/prometheus/client_python you should use that, I think that they don't support protobuffers, and only plain text protocol.

Thank you!
